const QuotesList = [
    { id: 1, author: "Aristotle", quote: "Life is what happens when you're busy making other plans.", category: "Friendship" },
    { id: 2, author: "Oscar Wilde", quote: "Believe you can and you're halfway there.", category: "Love" },
    { id: 3, author: "Mark Twain", quote: "Happiness is not something ready made. It comes from your own actions.", category: "Love" },
    { id: 4, author: "Confucius", quote: "Success is not the key to happiness. Happiness is the key to success.", category: "Love" },
    { id: 5, author: "Maya Angelou", quote: "You miss 100% of the shots you don’t take.", category: "Love" },
    { id: 6, author: "Helen Keller", quote: "Happiness is not something ready made. It comes from your own actions.", category: "Success" },
    { id: 7, author: "Maya Angelou", quote: "Believe you can and you're halfway there.", category: "Friendship" },
    { id: 8, author: "Oscar Wilde", quote: "In the middle of every difficulty lies opportunity.", category: "Love" },
    { id: 9, author: "Confucius", quote: "You miss 100% of the shots you don’t take.", category: "Love" },
    { id: 10, author: "Aristotle", quote: "Life is what happens when you're busy making other plans.", category: "Motivation" },
    { id: 11, author: "Albert Einstein", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Wisdom" },
    { id: 12, author: "Confucius", quote: "Happiness is not something ready made. It comes from your own actions.", category: "Success" },
    { id: 13, author: "Albert Einstein", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Love" },
    { id: 14, author: "Maya Angelou", quote: "The purpose of our lives is to be happy.", category: "Motivation" },
    { id: 15, author: "Albert Einstein", quote: "You miss 100% of the shots you don’t take.", category: "Friendship" },
    { id: 16, author: "Helen Keller", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Happiness" },
    { id: 17, author: "Mark Twain", quote: "Believe you can and you're halfway there.", category: "Wisdom" },
    { id: 18, author: "Oscar Wilde", quote: "You miss 100% of the shots you don’t take.", category: "Life" },
    { id: 19, author: "Aristotle", quote: "The purpose of our lives is to be happy.", category: "Life" },
    { id: 20, author: "Aristotle", quote: "Life is what happens when you're busy making other plans.", category: "Life" },
    { id: 21, author: "Oscar Wilde", quote: "In the middle of every difficulty lies opportunity.", category: "Wisdom" },
    { id: 22, author: "Mark Twain", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Love" },
    { id: 23, author: "Oscar Wilde", quote: "In the middle of every difficulty lies opportunity.", category: "Wisdom" },
    { id: 24, author: "Albert Einstein", quote: "The purpose of our lives is to be happy.", category: "Life" },
    { id: 25, author: "Confucius", quote: "In the middle of every difficulty lies opportunity.", category: "Wisdom" },
    { id: 26, author: "Helen Keller", quote: "Life is what happens when you're busy making other plans.", category: "Wisdom" },
    { id: 27, author: "Confucius", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Motivation" },
    { id: 28, author: "Oscar Wilde", quote: "The purpose of our lives is to be happy.", category: "Love" },
    { id: 29, author: "Mark Twain", quote: "Success is not the key to happiness. Happiness is the key to success.", category: "Friendship" },
    { id: 30, author: "Confucius", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Life" },
    { id: 31, author: "Oscar Wilde", quote: "Get busy living or get busy dying.", category: "Happiness" },
    { id: 32, author: "Aristotle", quote: "Believe you can and you're halfway there.", category: "Happiness" },
    { id: 33, author: "Oscar Wilde", quote: "Success is not the key to happiness. Happiness is the key to success.", category: "Motivation" },
    { id: 34, author: "Helen Keller", quote: "The only way to do great work is to love what you do.", category: "Love" },
    { id: 35, author: "Oscar Wilde", quote: "In the middle of every difficulty lies opportunity.", category: "Motivation" },
    { id: 36, author: "Aristotle", quote: "Life is what happens when you're busy making other plans.", category: "Friendship" },
    { id: 37, author: "Oscar Wilde", quote: "Life is what happens when you're busy making other plans.", category: "Happiness" },
    { id: 38, author: "Albert Einstein", quote: "The only way to do great work is to love what you do.", category: "Success" },
    { id: 39, author: "Confucius", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Happiness" },
    { id: 40, author: "Mark Twain", quote: "Happiness is not something ready made. It comes from your own actions.", category: "Life" },
    { id: 41, author: "Mark Twain", quote: "Success is not the key to happiness. Happiness is the key to success.", category: "Success" },
    { id: 42, author: "Maya Angelou", quote: "Believe you can and you're halfway there.", category: "Love" },
    { id: 43, author: "Albert Einstein", quote: "The purpose of our lives is to be happy.", category: "Happiness" },
    { id: 44, author: "Maya Angelou", quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", category: "Success" },
    { id: 45, author: "Helen Keller", quote: "Believe you can and you're halfway there.", category: "Love" },
    { id: 46, author: "Maya Angelou", quote: "The only way to do great work is to love what you do.", category: "Success" },
    { id: 47, author: "Helen Keller", quote: "In the middle of every difficulty lies opportunity.", category: "Friendship" },
    { id: 48, author: "Aristotle", quote: "You miss 100% of the shots you don’t take.", category: "Friendship" },
    { id: 49, author: "Confucius", quote: "Happiness is not something ready made. It comes from your own actions.", category: "Friendship" },
    { id: 50, author: "Oscar Wilde", quote: "The purpose of our lives is to be happy.", category: "Happiness" }
];